version: "3.9"
services:
  gateway:
    build: 
      context: ./gateway
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1111
  user_service:
    build: ./user_service
    ports:
      - "5002:5002"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  java_service:
    build: ./EchoServer
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=5000
  user_db:
    image: postgres
    restart: always
    ports:
      - "1234:1234"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - user_db:/var/lib/postgresql/data
  tasks_db:
    image: postgres
    restart: always
    ports:
      - "1235:1235"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - tasks_db:/var/lib/postgresql/data
volumes:
  user_db:
    driver: local
  tasks_db:
    driver: local
  logvolume01: {}
