version: "3.9"
services:
  gateway:
    build: 
      context: ./gateway/
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - USER_SERVICE_URL=localhost:5002
      - JAVA_SERVER_URL=localhost:5000
  user-service:
    build: 
      context: ./user_service/
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - TASKS_DATABASE_URL=postgresql://postgres:postgres@user-db:5432/test-user_db
  java-service:
    build: 
      context: ./EchoServer/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JDBC_DATABASE_URL=jdbc:postgresql://tasks-db:5432/test-tasks-db?user=postgres&password=postgres
  user-db:
    image: postgres
    restart: always
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - user-db:/var/lib/postgresql/data
  tasks-db:
    image: postgres
    restart: always
    ports:
      - "1235:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-tasks-db
    volumes: 
      - tasks-db:/var/lib/postgresql/data
volumes:
  user-db:
    driver: local
  tasks-db:
    driver: local
  logvolume01: {}
