version: "3.9"
services:
  gateway:
    build: 
      context: ./gateway/
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - USER_SERVICE_URL=localhost:5002
      - JAVA_SERVER_URL=localhost:5000
  user-service:
    build: 
      context: ./user_service/
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - TASKS_DATABASE_URL=postgresql://postgres:postgres@user-db:5432/
  java-service:
    build: 
      context: ./EchoServer/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - tasks-db
    environment:
      - PORT=5000
      - JDBC_DATABASE_URL=jdbc:postgresql://tasks-db:5432/?user=postgres&password=postgres
  user-db:
    image: postgres
    restart: always
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes: 
      - user-db:/var/lib/postgresql/data
  tasks-db:
    image: postgres
    restart: always
    ports:
      - "1235:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - tasks-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init-tasks-db.sql
volumes:
  user-db:
    driver: local
  tasks-db:
    driver: local
  logvolume01: {}
